### ISSUE TITLE
false branding - not the official site

### ISSUE THREAD

**Issue by probablyjassin** [Chess-Anarchy/Chess-Anarchy.github.io#12]
I'm the co-creator of the official upcoming r/AnarchyChess website that we are planning among the moderation team of the subreddit. This website is claiming that the website is official, which is not true.

We want you to remove this false claim as quickly as possible. Please refrain from branding yourselves as 'official' in the name of r/AnarchyChess in the future.

**Comment by uPos3odon08** [comment]
to our defense, while the project was alive we had most of the subreddit behind us and the mods but the issue has been resolved

**Comment by probablyjassin** [comment]
No worries, thank you!
